import Head from "next/head";
import { useState } from "react";
import { BlockMath, InlineMath } from "react-katex";
import Table from "~/components/table";

export default function Home() {
  const [n, setN] = useState("1000");

  return (
    <>
      <Head>
        <title>Complexity</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-black text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Complexity
          </h1>
          <p>
            How long does it take these devices to do execute a{" "}
            <InlineMath math="\Theta(f(n))" /> algorithm when{" "}
            <InlineMath math="n =" />
            <input
              className="ml-2 mr-1 rounded-md px-2 py-1 text-black"
              type="number"
              value={n}
              min={10}
              onChange={(e) => setN(e.target.value)}
            />
            ?
          </p>
          <div>
            <BlockMath math="\text{time (s)} = f(n)~\text{instructions} \times \dfrac{1~\text{cycle}}{\text{instruction}} \div \text{clock rate}" />
          </div>
          <Table n={Number(n)} />
        </div>
      </main>
    </>
  );
}
